### ISSUE TITLE
Activate GitHub Pages

### ISSUE THREAD

**Issue by ratnanil** [Postlews/Project-Proposal-#8]
Hi there! 

I see that you don't seem to be working in this repo, your last commit was quite a while ago. What is the issue? 

Also, I've noticed that you haven't yet activated GitHub Pages on your repo. Can you do this? All you need to do is go to the settings of your repo, go the tab "Pages" and activate GitHub Pages by choosing your branch (`main` or `master`) and then the folder `root` (see screenshot below). The green box will appear if you click on save.

If you have any questions, please book a session with me via https://calendly.com/rata-zhaw/ or Nikos https://calendly.com/bako-1/

![gh-pages](https://raw.githubusercontent.com/ComputationalMovementAnalysis/Slides/master/images/gh-pages-2.png)

**Comment by ratnanil** [comment]
Steele, can you please activate Github Pages?

**Comment by Postlews** [comment]
Apologies for the confusion. I believe I have now activated Github pages.

**Comment by ratnanil** [comment]
You have! this link now works: https://Postlews.github.io/Project-Proposal-/Semesterproject.html 

But it's the old version of the report, can you resolve issue #9 as well?

**Comment by Postlews** [comment]
Is [FinalSemesterProject.Rmd](https://github.com/Postlews/Project-Proposal-/blob/Main/FinalSemesterProject.Rmd)
[Push request 07-07](https://github.com/Postlews/Project-Proposal-/commit/cb1ba1d8ad5665a5c6043ce73d3777459c16f92c) not correct?
"Push Request 07-07"
